# Site Settings
title: Miracuse SRD
email: thenaticswest@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A swords and sorcery tabletop RPG.
domain: miracuse.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://miracuse.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: ""

# Exclusions
exclude:
  [
    "README.md",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "node_modules/",
    "package.json",
    "package-lock.json",
    "prettierrc.json",
    ".prettierignore",
    "kit_convert.py",
    "miracuse_kits.xlsx",
    "Makefile",
    "devel/",
  ]

# Build settings
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed

# Global Variables
alchemist_color: "#268bd2"
soldier_color: "#d28445"
mage_color: "#953553"
scoundrel_color: "#90a959"
paladin_color: "#d4af37"
