# Site settings
title: Miracuse SRD
email: thenaticswest@gmail.com
description: A swords and sorcery tabletop RPG.
domain: miracuse.github.io
url: https://miracuse.github.io
exclude:
  [
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "node_modules/",
    "package.json",
    "package-lock.json",
    "prettierrc.json",
    ".prettierignore",
    "kit_convert.py",
    "miracuse_data.xlsx",
    ".~lock.miracuse_data.xlsx#",
    "Makefile",
    "devel/",
    "resources/"
  ]

# Theme Settings
remote_theme: just-the-docs/just-the-docs
# theme: "just-the-docs"
search_enabled: false
# color_scheme: dark

# Plugins
plugins:
  - jekyll-relative-links

# Global Variables
alchemist_color: "#268bd2"
soldier_color: "#d28445"
mage_color: "#953553"
scoundrel_color: "#90a959"
paladin_color: "#d4af37"
warlock_color: "#871F78"
